import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { createOpenApiDocument } from '../../packages/api-contracts/src/openapi.js';

const root = process.cwd();
const check = process.argv.includes('--check');
execFileSync('forge', ['build', '--root', 'chain'], { cwd: root, stdio: 'inherit' });

function abiSource(artifact: string, exportName: string): string {
  const value = JSON.parse(readFileSync(resolve(root, artifact), 'utf8')) as { abi: unknown };
  return `// Generated by pnpm generate. Do not edit.\nexport const ${exportName} = ${JSON.stringify(value.abi, null, 2)} as const;\n`;
}
const outputs = new Map<string, string>([
  [
    'packages/chain-artifacts/src/generated/vehicle-nft.ts',
    abiSource('chain/out/VehicleNFT.sol/VehicleNFT.json', 'vehicleNftAbi'),
  ],
  [
    'packages/chain-artifacts/src/generated/motorcove-escrow.ts',
    abiSource('chain/out/MotorCoveEscrow.sol/MotorCoveEscrow.json', 'motorCoveEscrowAbi'),
  ],
  [
    'packages/api-contracts/generated/openapi.json',
    `${JSON.stringify(createOpenApiDocument(), null, 2)}\n`,
  ],
]);
const drift: string[] = [];
for (const [relativePath, content] of outputs) {
  const destination = resolve(root, relativePath);
  if (check) {
    let current = '';
    try {
      current = readFileSync(destination, 'utf8');
    } catch {
      /* missing is drift */
    }
    if (current !== content) drift.push(relativePath);
  } else {
    mkdirSync(dirname(destination), { recursive: true });
    writeFileSync(destination, content);
  }
}
if (drift.length) {
  console.error(`Generated artifact drift:\n${drift.join('\n')}`);
  process.exit(1);
}
console.log(check ? 'Generated artifacts match source.' : `Generated ${outputs.size} artifacts.`);
